export const HOTEL_LIST_REQUEST = 'dashboard/HOTEL_LIST_REQUEST';
export const HOTEL_LIST_RESPONSE = 'dashboard/HOTEL_LIST_RESPONSE';
export const HOTEL_LIST_FAILURE = 'dashboard/HOTEL_LIST_FAILURE';

export const MODIFY_BOOKING_REQUEST = 'analytics/MODIFY_BOOKING_REQUEST';
export const MODIFY_BOOKING_RESPONSE = 'analytics/MODIFY_BOOKINGS_RESPONSE';
export const MODIFY_BOOKING_FAILURE = 'analytics/MODIFY_BOOKING_FAILURE';

export const GET_BOOKING_DETAILS_REQUEST = 'analytics/GET_BOOKING_DETAILS_REQUEST';
export const GET_BOOKING_DETAILS_RESPONSE = 'analytics/GET_BOOKING_DETAILS_RESPONSE';
export const GET_BOOKING_DETAILS_FAILURE = 'analytics/GET_BOOKING_DETAILS_FAILURE';

export const DELETE_BOOKING_REQUEST = 'analytics/DELETE_BOOKING_REQUEST';
export const DELETE_BOOKING_RESPONSE = 'analytics/DELETE_BOOKING_RESPONSE';
export const DELETE_BOOKING_FAILURE = 'analytics/DELETE_BOOKING_FAILURE';